Featurise a doc

In [7]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
count=CountVectorizer()
docs = np.array(['The sun is shining',
                 'The weather is sweet',
                 'The sun is shining, the weather is sweet, and one and one is two'])
bag=count.fit_transform(docs).toarray()

In [9]:
print(count.vocabulary_)
print(bag)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}
[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


TF-IDF Transfomer

In [11]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf=TfidfTransformer(use_idf=True, norm='l2', smooth_idf=True)
print(tfidf.fit_transform(bag).toarray())

[[0.         0.43370786 0.         0.55847784 0.55847784 0.
  0.43370786 0.         0.        ]
 [0.         0.43370786 0.         0.         0.         0.55847784
  0.43370786 0.         0.55847784]
 [0.50238645 0.44507629 0.50238645 0.19103892 0.19103892 0.19103892
  0.29671753 0.25119322 0.19103892]]


Tokenize the Doc

In [37]:
from nltk.stem.porter import PorterStemmer 
porter = PorterStemmer()  
def stemmer_tokenize(text):     
    return [porter.stem(word) for word in text.split()]  
stemmer_tokenize('coders like coding and thus they code')

['coder', 'like', 'code', 'and', 'thu', 'they', 'code']

In [34]:
import pandas as pd
df = pd.read_csv(r"C:\Users\ADITYA\Desktop\IMDB Dataset.csv")

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(strip_accents=None,lowercase=False,tokenizer=stem_tokenize,use_idf=True, norm='l2', smooth_idf=True)
Y=df.sentiment.values
X=tfidf.fit_transform(df.review)

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,random_state=1)

In [42]:
import pickle
from sklearn.linear_model import LogisticRegressionCV
clf = LogisticRegressionCV(cv = 5,scoring = 'accuracy',random_state=0,n_jobs=-3,verbose=3,max_iter=300).fit(X_train, y_train)

[Parallel(n_jobs=-3)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=-3)]: Done   2 out of   5 | elapsed:  3.0min remaining:  4.5min
[Parallel(n_jobs=-3)]: Done   5 out of   5 | elapsed:  3.1min finished


In [43]:
#saving the model 
saved_model = open('saved_model.sav','wb')
pickle.dump(clf, saved_model)
saved_model.close()

In [44]:
filename="saved_model.sav"
saved_clf=pickle.load(open(filename,'rb'))
saved_clf.score(X_test,y_test)

FileNotFoundError: [Errno 2] No such file or directory: 'Desktop/Winsem/NLP/saved_model.sav'